# Generated by Django 5.2 on 2025-04-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0002_alter_reservation_floor_alter_reservation_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
