# Generated by Django 5.2 on 2025-04-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkingapp', '0003_alter_parking_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'parking', 'floor', 'spot')},
        ),
    ]
